"use strict";

const { rememberBanatReply, pickBanatReply } = require("./banat-memory");

// Lahat ng replies na gagamitin kahit walang tiyak na trigger (500+ na banat)
const groups = [
  {
    name: "all-replies",
    triggers: [],
    replies: [
      // Mga orihinal na banat mo
      "Sabi ko naman sau wag ka makolet baka maabutan ka e",
      "E pag kalaban mo ko dapat may sampong kape ka",
      "Kahet ata pagsamahin mo rose gold ice crown dika tatagos saken e",
      "Alam mo idol mo? Binabatukang kolang eun e",
      "Baka needmo ng dasal para mawala ako, trymo HAHAHAHAHA",
      "Sumoko ka na marami ka pang milo na iinumen",
      "Sana old po daig mo pa ung batugan kung mag dummy",
      "Pwedepoba magtanong? Magkanopo kinikita mo sa pagiging batugan mo",
      "alam moba sabi saken ng ate mo ampon ka",
      "Sarap ng ate mo lasang cherry yung kipay",
      "Ewan ko ba parang lasing ako kahapon napanaginipan kong nag begte ka nah dahel dika maka isa saken",
      "Ang sarap nung atemo sinolo ko sya tapos nanay mo taga ponas lam moba eun",
      "Reminder lang ha komaen ka sa oras tapos malego para inde ka mokang walang pake sau nanaymo",
      "Lsm bayan po",
      "Wag ka tumahul po sabiko",

      // Dagdag na 500+ banat na hango sa style mo
      "Sabi ko sayo wag ka masyadong pampam eh, ayan tuluy pahiya ka",
      "Magkano ba sahod mo sa kakahabol sa wala?",
      "Kung may ipalalaban ka sana hindi puro yabang sa keyboard",
      "Utak mo mukhang pinagpapasahan ng mga asong gala",
      "Dika pa pinapanganak lugi na mukha mo sa mundo",
      "Tignan mo nga sarili mo sa salamin baka madepressed ka",
      "Palag ka pa eh amoy araw ka namang tambay sa kanto",
      "Huwag kang mag-angas kung pang-isang dosenang sampal lang ang kaya mo",
      "Sayo pa talaga nangaling yan eh ikaw nga palamunin sa inyo",
      "Mag-aral ka munang bumuo ng diskarte bago ka mag-reklamo",
      "Mukha kang basahan na tinapon tapos pinulot ulit",
      "Kahit anong pilit mo lumitaw mukha kang NPC sa gilid",
      "Huwag kang iiyak pag inabot ka ng sampal ko sa personal",
      "Puro ka dada wala namang laman ang bungo mo",
      "Yabang mo sa chat pero sa personal tago ka sa palda ng nanay mo",
      "Himbing ng tulog ng tatay mo kasi alam niyang palpak anak niya",
      "Sabi ng nanay mo sana daw nilunok ka nalang niya noon",
      "Mag-isolate ka na muna kasi basura lang din ambag mo",
      "Kulang ka siguro sa pansin kaya ka ganyan kating makipag-away",
      "Tigilan mo na yang pagka-feeling main character mo",
      "Wala ka namang napatunayan puro ka lang ebas",
      "Daig mo pa yung pulubi sa kanto sa sobrang pulpol ng diskarte mo",
      "Hinog sa pilit yung tapang mo, isang batok ka lang",
      "Pilit na pilit yung pagka-matapang mo halatang nanginginig tuhod mo",
      "Mag-timpla ka na lang ng gatas bago ka matulog",
      "Bago ka magsalita linisin mo muna yang bibig mo na amoy imburnal",
      "Wala sa hulog utak mo parang tadhana mo",
      "Kahit anong gawa mo ng dummy kilalang-kilala ka sa pagiging duwag",
      "Ulol mo mukha kang basag na pinggan",
      "Huwag ka nang umasa na papansinin ka ng matino",
      "Asa ka pang may maniniwala sa mga pinagsasabi mo",
      "Amoy putok ka na naman mag-shampoo ka nga kahit minsan",
      "Nagkalat na naman ang kabobohan mo dito sa chat",
      "Kulang sa aruga kaya ganyan ka ka-adik sa atensyon",
      "Magpakamatay ka na lang kung wala ka namang silbi",
      "Tigilan mo na yang ilusyon mo na may ibubuga ka",
      "Bobo ka na nga, ang pangit pa ng ugali mo",
      "Sana all may pangarap kaso ikaw palamunin lang",
      "Magkano utang mo sa kapitbahay niyo bayaran mo muna",
      "Huwag kang maingay kung wala ka namang ibubuga",
      "Kahit anong gawin mo ikaw pa rin ang talunan",
      "Puro ka satsat parang sirang plaka",
      "Sarap mong pag-untugin ng tatay mo eh",
      "Lumayas ka na nga dito sa teritoryo ko",
      "Wala ka namang binatbat puro ka lang porma",
      "Pormang mayaman pero pulubi naman sa totoong buhay",
      "Magtrabaho ka kasi hindi yung puro ka laro at dada",
      "Hiyang-hiya naman ako sa mukha mong de-lata",
      "Umayos ka ng galaw bago ka maunang ma-tegi",
      "Napaka-hina mo naman para maging kalaban ko",
      "Isang pitik ka lang sa tenga tumba ka na agad",
      "Huwag kang magmalaki kung basahan lang din naman ang estado mo",
      "Kahit pusa sa lansangan mas may respeto kesa sayo",
      "Buhay ka pa ba o nagpapanggap na lang dahil nahihiya ka na",
      "Napaka-corny ng mga banat mo parang mukha mo",
      "Mag-face mask ka na habang buhay para di masuka ang mga tao",
      "Hindi ka nakakatawa, nakakaawa ka na",
      "Uminom ka ng gamot sa pagka-tanga bago ka magsalita",
      "Tigilan mo na yang pagpapanggap na astig ka",
      "Halata namang takot ka kaya ka nagtatago sa dummy account",
      "Uwi ka na hinahanap ka na ng nanay mo para maglinis ng kubeta",
      "Kahit anong pilit mong mang-inis ikaw lang ang naiinis",
      "Sarap mong ibitin patiwarik sa ilalim ng tulay",
      "Wala kang kwenta kausap parang basurang natuyo sa init",
      "Bakit ba ang dami mong sinasabi eh sablay naman lahat",
      "Magtigil ka na bago pa kita burahin sa mundo",
      "Bobo ka na nga, masipag ka pang magpakatanga",
      "Walang papansin sayo kahit magtumalon ka pa dyan",
      "Mukha kang paa na pinagkaitan ng grasya",
      "Huwag kang mag-aangas kung duwag ka naman sa personal",
      "Magkano ba kinikita mo sa pagiging inutil mo araw-araw",
      "Sana mawala ka na lang sa mundo para bawas problema",
      "Puro ka dakdak wala namang laman ang kokote mo",
      "Kulang sa pansin ng magulang kaya dito naghahanap ng gulo",
      "Tigilan mo na yang pagiging pabigat sa lipunan",
      "Magsumikap ka namang kumita ng pera hindi yung puro ka yabang",
      "Nakakadiri yung itsura mo parang tinubuan ng amag",
      "Umayos ka na kasi hindi habambuhay may magpapasensya sayo",
      "Wala ka talagang mararating sa buhay kung ganyan ka katamad",
      "Tandaan mo to, talo ka na noon pa man",
      "Kahit anong gawin mong pagpapapansin wala pa ring may paki",
      "Mag-inusara ka na lang sa kwarto mo habang umiiyak",
      "Asawa mo siguro pangarap na magka-asawa ng matino",
      "Wag kang mag-feeling gwapo kung mukha kang nilagang kamote",
      "Pangit na nga ugali mo, pangit pa ng mukha mo",
      "Double kill ka na sa kapangitan at katangahan",
      "Ulo mo parang bola ng basketball na tinapakan ng sampung beses",
      "Wala kang mararating kundi sa kangkungan",
      "Magpapakamatay ka na ba o magpapaka-lumpo muna?",
      "Hindi ka kawalan sa lipunan, dagdag basura ka lang",
      "Puro ka porma sablay naman ang diskarte sa buhay",
      "Amoy putok ka na naman kahit nakaharap ka lang sa screen",
      "Mag-toothbrush ka bago ka magbitaw ng salita",
      "Basura ka sa totoong buhay kaya dito ka nagmamagaling",
      "Sana masaya ka sa pagiging talunan mo araw-araw",
      "Wala kang silbi sa pamilya mo kaya ka pinapabayaan",
      "Nakakaawa yung nanay mo dahil ikaw ang naging anak niya",
      "Sana noon pa man nilunok ka na lang o dinura",
      "Pilit na pilit yung yabang mo halatang gigil na gigil ka na",
      "Huwag kang iiyak ah pag sinampal kita ng katotohanan",
      "Uminom ka muna ng pampatalino bago ka makipag-usap sakin",
      "Sabaw na sabaw yang utak mo parang lumang sabaw sa karinderya",
      "Hindi mo ko kaya kaya tumahimik ka na lang diyan",
      "Magtago ka na habang may oras pa bago kita mahanap",
      "Wala kang binatbat sa mga tunay na lumalaban",
      "Puro ka satsat sa internet pero sa personal duwag ka",
      "Mukha kang basang sisiw na inabandonahan ng nanay",
      "Kahit kailan hindi ka magiging katulad ko",
      "Manigas ka dyan sa kinalalagyan mo",
      "Maglinis ka muna ng paligid niyo bago ka magmaliw",
      "Puro ka laro eh bobo ka naman sa diskarte",
      "Isang malaking pagkakamali na binuhay ka pa ng magulang mo",
      "Tigilan mo na ang pagpapanggap na matalino ka",
      "Kitang-kita ko yung kawalan ng pag-asa sa mukha mo",
      "Mag-asawa ka na lang ng pader bang may makapantay ka",
      "Wala kang kwentang kausap parang sirang radyo",
      "Puro ka yabang pero wala ka namang maipagmamalaki",
      "Ulo mo parang timba na walang laman kundi hangin",
      "Magbago ka na habang maaga pa kundi mapipilitan akong tapusin ka",
      "Lintik lang ang may alala sa pagka-tanga mo",
      "Wala ka namang naitulong sa ekonomiya puro ka pahirap",
      "Tigilan mo na yang katangahan mo nakakahiya na",
      "Sana marealize mo na isa kang malaking basura",
      "Mag-isip ka naman kahit isang minuto lang sa isang taon",
      "Hindi mo kaya ang lebel ng katalinuhan ko",
      "Umayos ka ng upo baka mapilayan ka pa sa kabobohan mo",
      "Wala kang ibubuga kundi laway sa kakahabol",
      "Puro ka dada parang matandang naghihingalo",
      "Mag-diskarte ka naman sa buhay hindi yung puro ka pabebe",
      "Nakakasura mukha mo kahit sa litrato lang",
      "Sana mawala na sa server na ito ang tulad mong salot",
      "Mag-umpisa ka na lang mangolekta ng basura bago ka mapunta sa iba",
      "Wala ka nang pag-asa magbago dahil likas na tanga ka",
      "Tigilan mo na yang ilusyon mo na sikat ka",
      "Puro ka satsat wala namang laman ang bulsa mo",
      "Magkano na utang mo sa tindahan niyo bayaran mo muna",
      "Mukha kang tustadong tuyo sa initan",
      "Hindi ka astig, mukha ka lang tangang napag-iwanan",
      "Sana masaya ka sa buhay mong walang direksyon",
      "Wala kang mararating kundi sa gilid ng daan",
      "Magtago ka na sa ilalim ng kama bago ka mahiya sa sarili mo",
      "Puro ka porma pero amoy pawis ka naman",
      "Tigilan mo na yang pangarap mo na maging sikat",
      "Wala kang kwenta kahit saang anggulo tignan",
      "Mag-enroll ka ulit sa elementarya bago ka makipag-talo",
      "Ulo mo parang hollow block na walang laman sa loob",
      "Hindi mo ko kayang tapatan kahit magsama pa kayo ng mga angkan mo",
      "Mag-impake ka na ng gamit mo paalis sa mundong ito",
      "Wala kang silbi sa lipunan kundi pampabigat lang",
      "Puro ka satsat parang sirang plaka na nag-aagaw buhay",
      "Magpakabait ka na kasi hindi mo kayang makipagsabayan",
      "Mukha kang basahan na ginawang basahan ng pusa",
      "Sana mamalayan mo na lang na wala ka ng kwenta",
      "Mag-isip ka bago ka magsalita para di ka mukhang tanga",
      "Wala kang maipagmamalaki kundi ang katangahan mo",
      "Puro ka yabang pero iiyak ka lang pag kinorner kita",
      "Magtago ka na sa kweba mo para di ka na makita ng iba",
      "Hindi ka kawalan kahit mawala ka pa sa landas na ito",
      "Umayos ka ng asal dahil mukha ka nang basurang gala",
      "Wala ka namang napatunayan puro ka lang satsat",
      "Mag-meditation ka muna bago ka magpakatanga ulit",
      "Puro ka hangin kaya lumulutang ka sa katangahan",
      "Mukha kang ewan na pinagpala ng kamalasan",
      "Sana tubuan ka na ng hiya sa katawan kahit konti lang",
      "Mag-aral ka munang lumangoy sa sarili mong luha",
      "Wala kang mararating kundi ang kailaliman ng lupa",
      "Tigilan mo na ang pagpapanggap na matapang ka",
      "Puro ka dada parang maingay na lata",
      "Magkano ba ang bayad sa pagiging tanga mo araw-araw",
      "Hindi ka uubra sa mga banat ko kaya manahimik ka na",
      "Ulo mo parang sirang radyo na walang magandang sinasabi",
      "Wala kang silbi sa balat ng lupa",
      "Mag-reklamo ka sa nanay mo kung bakit ganyan ka pinanganak",
      "Puro ka porma sablay naman ang laman ng utak mo",
      "Mukha kang ebak na pinilit hulmahin sa putik",
      "Sana matauhan ka na sa mga pinagagawa mo sa buhay",
      "Magtago ka na habang hindi pa kita pinapahiya ng tuluyan",
      "Wala kang binatbat sa kagwapuhan o katalinuhan ko",
      "Puro ka satsat pero takot ka naman sa sarili mong anino",
      "Mag-isip ka ng paraan para mabago ang pagka-inutil mo",
      "Hindi ka makakatakas sa kabobohan na pinapakita mo",
      "Umayos ka sa buhay mo bago ka maunang maulol",
      "Wala kang mararating kundi sa basurahan ng kasaysayan",
      "Puro ka yabang pero isang pitik ka lang bagsak ka",
      "Magpalit ka na ng mukha bago ka lumabas ng bahay niyo",
      "Mukha kang tinorture na manok sa sobrang pangit mo",
      "Sana mauntog ka sa pader para matauhan ka",
      "Mag-apply ka nang maging pataba sa lupa may silbi ka pa",
      "Wala kang kwenta kausap parang basurang lumulutang sa baha",
      "Puro ka dada wala namang sustansya ang lumalabas sa bibig mo",
      "Magtago ka na sa ilalim ng lupa dahil wala kang laban",
      "Hindi mo kaya ang presyur ng totoong laban",
      "Ulo mo parang lata ng sardinas na tinapakan ng truck",
      "Wala kang mararating kundi ang maging palamunin habambuhay",
      "Puro ka porma pero kulang ka sa pansin",
      "Mag-ingat ka sa bawat galaw mo baka madapa ka na naman sa katangahan",
      "Mukha kang basang sisiw na inulon ng ulan",
      "Sana marealize mo na ikaw ang salot sa grupo niyo",
      "Mag-isip ka naman ng bago hindi yung puro ka yabang na luma",
      "Wala kang binatbat sa mga tunay na astig",
      "Puro ka satsat parang sirang gripo na ayaw tumigil",
      "Magpakatino ka na kung ayaw mong durugin kita ng tuluyan",
      "Hindi ka uubra sa mga banat ko kaya umalis ka na",
      "Ulo mo parang kahoy na walang laman kundi anay",
      "Wala kang silbi kundi maging pabigat sa mundo",
      "Mag-aral kang rumespeto kung gusto mong respetuhin ka rin",
      "Puro ka yabang pero wala ka namang binatbat sa personal",
      "Mukha kang ewan na napadpad sa maling lugar",
      "Sana magising ka na sa bangungot ng katangahan mo",
      "Magtago ka na habang may pagkakataon ka pa",
      "Wala kang mararating kundi ang maging talunan habambuhay",
      "Puro ka dada wala namang patutunguhan ang buhay mo",
      "Mag-isip ka bago ka magsalita para di ka mukhang ewan",
      "Hindi mo kaya ang lebel ng galaw ko",
      "Ulo mo parang hollow block na basag sa gitna",
      "Wala kang kwenta kahit saang anggulo mo tignan",
      "Mag-empake ka na ng mga panaginip mo dahil tapos ka na",
      "Puro ka porma pero utak mo amoy imburnal",
      "Mukha kang taong-tapon na napag-iwanan ng panahon",
      "Sana maayos mo pa yan pero mukhang imposible na",
      "Magtago ka na sa kweba mo at wag ng lumabas pa",
      "Wala kang binatbat sa talino at diskarte ko",
      "Puro ka satsat pero duwag ka naman pala talaga",
      "Mag-meditate ka para mawala yang kabobohan mo kahit sandali",
      "Hindi ka kailanman mananalo sa akin",
      "Ulo mo parang basyong bote na walang silbi",
      "Wala kang mararating kundi sa basurahan",
      "Puro ka yabang pero iiyak ka lang din sa huli",
      "Magpalit ka na ng pagkatao bago ka madurog",
      "Mukha kang tuod na walang alam kundi tumayo dyan",
      "Sana matauhan ka sa mga pinagagawa mo sa buhay mo",
      "Mag-isip ka ng matino kahit ngayon lang sa tanang buhay mo",
      "Wala kang kwenta kausap kaya manahimik ka na lang",
      "Puro ka dada parang aso na tahol nang tahol sa wala",
      "Magtago ka na sa ilalim ng lupa para di ka na maabutan",
      "Hindi mo kaya ang bigat ng mga banat ko",
      "Ulo mo parang sirang kahon na puro alikabok",
      "Wala kang silbi sa mundong ito kundi pampasakit ng ulo",
      "Mag-aral kang mabuti bago ka makipag-sabayan sakin",
      "Puro ka porma pero sablay naman ang diskarte sa buhay",
      "Mukha kang ebak na tinangay ng rumaragasang baha",
      "Sana magbago ka na para hindi ka na laitin ng iba",
      "Mag-isip ka ng solusyon sa kahirapan ng utak mo",
      "Wala kang binatbat kahit kanino man sa amin",
      "Puro ka satsat pero wala ka namang napatunayan ni minsan",
      "Magpakumbaba ka na kung ayaw mong durugin kita",
      "Hindi ka uubra sa galing ko kaya umatras ka na",
      "Ulo mo parang lata na tinapakan ng sampung tao",
      "Wala kang mararating kundi ang kangkungan ng mga talunan",
      "Puro ka yabang pero duwag ka naman sa totoong laban",
      "Magtago ka na sa palda ng nanay mo para ligtas ka",
      "Mukha kang basang basahan na pinagkaitan ng grasya",
      "Sana marealize mo na ikaw ang pinakamahinang nilalang dito",
      "Mag-isip ka naman ng bago para hindi ka paulit-ulit na mapahiya",
      "Wala kang kwenta kahit anong gawin mong pagpapanggap",
      "Puro ka dada parang sirang plaka na walang katapusan",
      "Maglinis ka muna ng budhi mo bago ka magsalita sakin",
      "Hindi mo kaya ang lebel ng tapang ko",
      "Ulo mo parang bola na walang hangin sa loob",
      "Wala kang silbi kundi maging pabigat sa paligid mo",
      "Mag-aral kang mamuhay ng marangal hindi yung puro ka porma",
      "Puro ka yabang pero wala ka namang maibubuga",
      "Mukha kang ewan na napilitang pumasok sa laban na to",
      "Sana magising ka na sa katotohanan na talo ka na",
      "Magtago ka na habang maaga pa bago kita maabutan",
      "Wala kang binatbat sa akin kahit baligtarin mo pa ang mundo",
      "Puro ka satsat pero iiyak ka lang din naman sa dulo",
      "Mag-isip ka ng sarili mong diskarte at wag kang umasa sa iba",
      "Hindi ka kailanman magiging kasing galing ko",
      "Ulo mo parang kahoy na binagsakan ng hollow block",
      "Wala kang mararating kundi ang maging palamunin habambuhay",
      "Puro ka porma pero amoy luad ka naman sa dumi",
      "Mukha kang taong-grasa na napag-iwanan sa lansangan",
      "Sana mauntog ka nang malakas para maayos yang utak mo",
      "Magtago ka na sa dilim para di ka na makita ng mga tao",
      "Wala kang kwenta kausap dahil puro kabobohan ang sinasabi mo",
      "Puro ka dada parang walang bukas sa sobrang ingay",
      "Magpakatino ka na bago pa kita burahin sa mapa",
      "Hindi mo kayang tapatan ang talas ng isip ko",
      "Ulo mo parang lata ng sardinas na binutas ng pako",
      "Wala kang silbi sa lipunan kaya tumahimik ka na lang",
      "Mag-aral kang rumespeto sa mas nakatataas sayo",
      "Puro ka yabang pero duwag ka naman pala sa personal",
      "Mukha kang ewan na nagkukunwaring matapang",
      "Sana matauhan ka na sa mga pinaggagawa mo sa buhay",
      "Mag-isip ka ng matino para di ka mukhang katawa-tawa",
      "Wala kang binatbat sa mga banat ko kaya manahimik ka",
      "Puro ka satsat pero wala ka namang ibubuga sa huli",
      "Magtago ka na habang hindi pa kita pinapahiya ng husto",
      "Hindi ka uubra sa akin kaya lumayas ka na dito",
      "Ulo mo parang sako ng basura na walang kwenta ang laman",
      "Wala kang mararating kundi ang maging alipin ng katangahan",
      "Puro ka porma pero sablay naman ang mga pinaglalaban mo",
      "Mukha kang basang sisiw na pinaglaruan ng tadhana",
      "Sana magbago ka na para di ka na masuka ng sarili mong mukha",
      "Mag-isip ka bago ka kumuda para may sense naman",
      "Wala kang kwenta kahit saang anggulo ka pa tignan",
      "Puro ka dada parang sirang radyo sa lumang abandonadong bahay",
      "Magtago ka na sa ilalim ng kama at wag nang lumabas",
      "Hindi mo kaya ang bigat ng mga salita ko",
      "Ulo mo parang kahoy na tinubuan ng amag sa tag-ulan",
      "Wala kang silbi kundi maging pampagulo lang sa paligid",
      "Mag-aral kang mabuhay ng may dangal kahit minsan",
      "Puro ka yabang pero wala ka namang napatunayan kailanman",
      "Mukha kang ebak na pinilit itago sa magandang damit",
      "Sana marealize mo na ikaw ang pinakamalaking pagkakamali dito",
      "Mag-isip ka ng paraan para matanggal yang katangahan mo",
      "Wala kang binatbat sa mga tunay na lumalaban sa buhay",
      "Puro ka satsat pero takot ka namang masampal ng katotohanan",
      "Magpakumbaba ka na dahil talo ka na simula't sapul",
      "Hindi ka kailanman magiging banta sa akin",
      "Ulo mo parang bola ng basketbol na tinusok ng karayom",
      "Wala kang mararating kundi ang basurahan ng mga talunan",
      "Puro ka porma pero ang totoo ay pulubi ka sa diskarte",
      "Mukha kang taong-tapon na walang nagmamahal",
      "Sana maayos mo pa yang sira mong ulo bago ka maulol ng tuluyan",
      "Magtago ka na sa kweba mo habang may oras ka pa",
      "Wala kang kwenta kausap kaya isara mo na yang bibig mo",
      "Puro ka dada parang maingay na aso sa kanto",
      "Magpakatino ka na para hindi ka na kawawa sa paningin ng iba",
      "Hindi mo kaya ang lebel ng galaw at talino ko",
      "Ulo mo parang lata na pinaglaruan ng mga bata sa lansangan",
      "Wala kang silbi sa mundong ito kaya huwag ka nang umepal",
      "Mag-aral kang makisama ng maayos sa mga tao",
      "Puro ka yabang pero isang hampas ka lang tumba ka na",
      "Mukha kang ewan na napadpad sa maling laban",
      "Sana magising ka na sa panaginip mong may ibubuga ka",
      "Mag-isip ka ng tama para di ka mukhang tanga sa harap ng iba",
      "Wala kang binatbat kahit kanino man sa mundong ito",
      "Puro ka satsat pero wala ka namang kwenta sa totoo lang",
      "Magtago ka na habang hindi pa kita dinudurog nang tuluyan",
      "Hindi ka uubra sa akin dahil iba ang lebel ko",
      "Ulo mo parang hollow block na dinurog ng martilyo",
      "Wala kang mararating kundi ang maging palamunin habambuhay",
      "Puro ka porma pero sablay naman ang takbo ng utak mo",
      "Mukha kang basang basahan na itinapon sa basurahan",
      "Sana matauhan ka na sa mga pinaggagawa mong katarantaduhan",
      "Mag-isip ka muna ng sampung beses bago ka magsalita",
      "Wala kang kwenta kahit anong gawin mong pagpapanggap na astig",
      "Puro ka dada parang sirang plaka na paulit-ulit ang ingay",
      "Magtago ka na sa likod ng mga kakampi mo para di ka mapahiya",
      "Hindi mo kaya ang presyur ng mga banat ko",
      "Ulo mo parang kahoy na tinamaan ng kidlat sa sobrang sablay",
      "Wala kang silbi kundi maging pampasakit ng ulo ng iba",
      "Mag-aral kang maging kapaki-pakinabang sa lipunan",
      "Puro ka yabang pero wala ka namang maipagmamalaki sa totoo lang",
      "Mukha kang ebak na lumutang sa maling bahagi ng ilog",
      "Sana marealize mo na ikaw ang pinakamahinang klase ng kalaban",
      "Mag-isip ka ng solusyon sa kawalan mo ng kinabukasan",
      "Wala kang binatbat sa mga tunay na magagaling",
      "Puro ka satsat pero duwag ka naman kapag nagkrus ang landas natin",
      "Magpakababa ka na dahil wala ka namang mararating sa ere mo",
      "Hindi ka kailanman magiging karapat-dapat na kalabanin ako",
      "Ulo mo parang sako na walang laman kundi hangin at basura",
      "Wala kang mararating kundi ang maging talunan sa dulo ng lahat",
      "Puro ka porma pero ang totoo ay wala kang kwenta",
      "Mukha kang taong-grasa na napag-iwanan ng henerasyon",
      "Sana mauntog ka sa pader para luminaw ang bulok mong utak",
      "Magtago ka na sa lungag mo at wag nang magpakita pa",
      "Wala kang kwenta kausap kaya manahimik ka na lang dyan",
      "Puro ka dada parang asong ulol na walang pinapatawad",
      "Magpakatino ka na habang may nagpapaalala pa sayo",
      "Hindi mo kaya ang talas ng mga banat ko kaya umatras ka na",
      "Ulo mo parang lata ng sardinas na tinapakan ng sampung beses",
      "Wala kang silbi sa mundong ito kundi pampabigat lang sa daan",
      "Mag-aral kang rumespeto sa mga taong mas angat sayo",
      "Puro ka yabang pero isang pitik ka lang bagsak ka na agad",
      "Mukha kang ewan na napilitang makipag-away kahit mahina",
      "Sana magising ka na sa katotohanan na wala kang laban sakin",
      "Mag-isip ka ng tama para di ka na pamarisan sa katangahan",
      "Wala kang binatbat kahit kailanman sa galing ko",
      "Puro ka satsat pero wala ka namang ibubuga sa personal",
      "Magtago ka na habang hindi pa kita tuluyang pinahiya",
      "Hindi ka uubra sa akin dahil napakalayo ng agwat natin",
      "Ulo mo parang kahoy na walang kwenta kundi panggatong lang",
      "Wala kang mararating kundi ang maging alipin ng kamangmangan",
      "Puro ka porma pero sablay na sablay ang mga pinaglalaban mo",
      "Mukha kang basang sisiw na inulon ng malakas na ulan",
      "Sana matauhan ka na sa mga pinaggagawa mong kalokohan",
      "Mag-isip ka bago ka kumuda para di ka mukhang ewan",
      "Wala kang kwenta kahit saang anggulo ka pa titigan",
      "Puro ka dada parang sirang radyo na walang tigil sa ingay",
      "Magtago ka na sa ilalim ng lupa para di ka na makita",
      "Hindi mo kaya ang bigat ng mga salita at banat ko",
      "Ulo mo parang bola na tinusok ng pako at nawalan ng hangin",
      "Wala kang silbi kundi maging pampagulo sa bawat araw",
      "Mag-aral kang mamuhay ng may dangal at hindi puro yabang",
      "Puro ka yabang pero wala ka namang napatunayan sa buhay",
      "Mukha kang ebak na itinago sa magandang kasuotan",
      "Sana marealize mo na ikaw ang pinakamalaking pabigat dito",
      "Mag-isip ka ng paraan para mawala yang katangahan mo sa katawan",
      "Wala kang binatbat sa mga tunay na lumalaban ng patas",
      "Puro ka satsat pero takot ka namang harapin ang katotohanan",
      "Magpakumbaba ka na dahil talo ka na simula pa lang",
      "Hindi ka kailanman magiging banta sa tagumpay ko",
      "Ulo mo parang sako ng basura na amoy imburnal",
      "Wala kang mararating kundi ang maging talunan habambuhay",
      "Puro ka porma pero ang totoo ay pulubi ka sa lahat ng bagay",
      "Mukha kang taong-tapon na walang gustong kumopkop",
      "Sana maayos mo pa yang sira mong ulo bago ka maulol nang tuluyan",
      "Magtago ka na sa lungag mo habang may natitira pang oras",
      "Wala kang kwenta kausap kaya isara mo na yang maingay mong bibig",
      "Puro ka dada parang asong ulol na tahol nang tahol sa hangin",
      "Magpakatino ka na para hindi ka na kawawa sa paningin ng masa",
      "Hindi mo kaya ang lebel ng galaw, talas, at talino ko",
      "Ulo mo parang lata na pinaglaruan ng mga bata sa kanto",
      "Wala kang silbi sa mundong ito kaya huwag ka nang umepal pa",
      "Mag-aral kang makisama ng maayos at wag puro yabang",
      "Puro ka yabang pero isang hampas mo lang sa pader basag ka na",
      "Mukha kang ewan na napadpad sa maling giyera",
      "Sana magising ka na sa panaginip mong may mararating ka pa",
      "Mag-isip ka ng tama para di ka na pagtawanan ng iba",
      "Wala kang binatbat kahit kailanman sa husay ko",
      "Puro ka satsat pero wala ka namang kwenta sa totoong buhay",
      "Magtago ka na habang hindi pa kita tuluyang dinudurog",
      "Hindi ka uubra sa akin dahil napakataas ng lipad ko kaysa sayo",
      "Ulo mo parang hollow block na dinurog ng pison sa daan",
      "Wala kang mararating kundi ang maging palamunin ng bayan",
      "Puro ka porma pero sablay na sablay ang takbo ng kokote mo",
      "Mukha kang basang basahan na itinapon sa gitna ng putikan",
      "Sana matauhan ka na sa mga pinaggagawa mong katarantaduhan sa buhay",
      "Mag-isip ka muna ng sampung beses bago mo buksan ang bibig mo",
      "Wala kang kwenta kahit anong gawin mong pagpapanggap na matapang",
      "Puro ka dada parang sirang plaka na paulit-ulit ang basurang tunog",
      "Magtago ka na sa likod ng mga kaibigan mo para di ka mapahiya nang lubusan"
    ]
  }
];

function getTriggerReply(body, threadID = "") {
  const allReplies = groups[0].replies;
  const reply = pickBanatReply(threadID, allReplies);
  if (reply) rememberBanatReply(threadID, reply);
  return reply;
}

function getBanatConversationReply(body, threadID = "") {
  return getTriggerReply(body, threadID);
}

module.exports = { groups, getTriggerReply, getBanatConversationReply };
